import { useCallback, useMemo, useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { apiSlice } from '../../../services/redux/api/apiSlice';
import { 
  EntityDefinition, 
  DynamicApiRoutes, 
  UseDynamicEntityReturn 
} from '../types';

/**
 * Custom hook for managing dynamic entity operations
 * Handles entity definition fetching, API route generation, and entity validation
 */
export const useDynamicEntity = (): UseDynamicEntityReturn => {
  const { entityName } = useParams<{ entityName: string }>();
  const navigate = useNavigate();
  const [entityDef, setEntityDef] = useState<EntityDefinition | null>(null);

  // Use RTK Query to fetch entity definitions
  const { data: entityDefData, isLoading: loading, error: queryError, refetch: fetchEntityDefinition } = apiSlice.useGetEntityDefinitionQuery(
    { entity_name: entityName },
    { skip: !entityName }
  );

  // Extract items from response
  const items = useMemo(() => {
    if (!entityDefData) return null;
    const data = (entityDefData as any)?.result || entityDefData;
    return data;
  }, [entityDefData]);

  const error = queryError ? (queryError as any) : null;

  // Update entity definition when data changes
  useEffect(() => {
    const itemsResult = Array.isArray(items) ? items : (items?.result || []);
    if (itemsResult && Array.isArray(itemsResult) && itemsResult.length > 0 && entityName) {
      // Find the specific entity definition that matches the entityName
      const definition = itemsResult.find((item: EntityDefinition) => item.entity_name === entityName);
      if (definition) {
        setEntityDef(definition);
      } else {
        // If no matching entity found, clear the definition
        setEntityDef(null);
      }
    }
  }, [items, entityName]);

  // RTK Query automatically fetches when entityName changes
  // No manual fetch needed

  // Entity definition route (for backward compatibility, using RTK Query identifier)
  const entityDefRoute = useMemo(() => ({
    identifier: 'GetEntityDefinition',
    method: 'POST',
    endpoint: '/entity_definition',
  }), []);

  // Generate optimized API routes for dynamic entity
  const dynamicApiRoutes = useMemo<DynamicApiRoutes | null>(() => {
    if (!entityName) return null;
    
    const baseEndpoint = `/${entityName}`;
    
    return {
      get: {
        method: 'POST',
        endpoint: baseEndpoint,
        identifier: `GetAll_${entityName}`,
      },
      create: {
        method: 'PUT',
        endpoint: baseEndpoint,
        identifier: `Add_${entityName}`,
      },
      update: {
        method: 'POST',
        endpoint: baseEndpoint,
        identifier: `Update_${entityName}`,
      },
      delete: {
        method: 'DELETE',
        endpoint: baseEndpoint,
        identifier: `Delete_${entityName}`,
      },
    };
  }, [entityName]);


  // Basic columns - dynamic columns will be generated by GenericCrudPage
  const defaultColumns = useMemo(() => [
    {
      title: 'ID',
      dataIndex: '_id',
      key: '_id',
      render: (text: string) => (
        <span style={{ 
          fontFamily: 'monospace', 
          fontSize: '13px',
          fontWeight: 500,
          color: '#1890ff'
        }}>
          {text.substring(0, 8)}...
        </span>
      ),
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => (
        <span style={{ fontSize: '13px', color: '#666' }}>
          {new Date(date).toLocaleDateString()}
        </span>
      ),
    },
    {
      title: 'Updated',
      dataIndex: 'updatedAt',
      key: 'updatedAt',
      render: (date: string) => (
        <span style={{ fontSize: '13px', color: '#666' }}>
          {new Date(date).toLocaleDateString()}
        </span>
      ),
    },
  ], []);

  // Validation helpers
  const isEntityValid = useMemo(() => {
    return Boolean(entityDef && entityDef.is_active);
  }, [entityDef]);

  const hasError = useMemo(() => {
    return error || (!loading && !isEntityValid);
  }, [error, loading, isEntityValid]);

  // Navigation helpers
  const goBack = useCallback(() => {
    navigate('/entities');
  }, [navigate]);

  const goToEntityDefinitions = useCallback(() => {
    navigate('/entity-definitions');
  }, [navigate]);

  return {
    // State
    entityName,
    entityDef,
    loading,
    error,
    hasError,
    isEntityValid,
    
    // Computed
    dynamicApiRoutes,
    defaultColumns,
    
    // Actions
    fetchEntityDefinition,
    goBack,
    goToEntityDefinitions,
    
    // Helpers
    entityDefRoute,
  };
};
