import { useCallback, useMemo, useState, useEffect } from 'react';
import { useDispatch } from 'react-redux';
import { useParams, useNavigate } from 'react-router-dom';
import { Dispatch } from 'redux';
import { dynamic_request, useDynamicSelector } from '../../../services/redux';
import { createApiRouteGetter } from '../../../helpers/Common_functions';
import { 
  EntityDefinition, 
  DynamicApiRoutes, 
  UseDynamicEntityReturn 
} from '../types';

/**
 * Custom hook for managing dynamic entity operations
 * Handles entity definition fetching, API route generation, and entity validation
 */
export const useDynamicEntity = (): UseDynamicEntityReturn => {
  const { entityName } = useParams<{ entityName: string }>();
  const navigate = useNavigate();
  const dispatch: Dispatch<any> = useDispatch();
  const [entityDef, setEntityDef] = useState<EntityDefinition | null>(null);

  // Memoized API route getter to prevent recreation
  const getApiRoute = useMemo(() => createApiRouteGetter('EntityDefinition'), []);
  const entityDefRoute = useMemo(() => getApiRoute('GetAll'), [getApiRoute]);

  // Fetch entity definition data
  const { loading, items, error } = useDynamicSelector(entityDefRoute.identifier);

  // Fetch entity definition when entityName changes
  const fetchEntityDefinition = useCallback(() => {
    if (entityName) {
      dispatch(
        dynamic_request(
          {
            method: entityDefRoute.method,
            endpoint: entityDefRoute.endpoint,
            data: { entity_name: entityName },
          },
          entityDefRoute.identifier
        )
      );
    }
  }, [entityName, dispatch, entityDefRoute]);

  // Update entity definition when data changes
  useEffect(() => {
    if (items?.result && Array.isArray(items.result) && items.result.length > 0 && entityName) {
      // Find the specific entity definition that matches the entityName
      const definition = items.result.find((item: EntityDefinition) => item.entity_name === entityName);
      if (definition) {
        setEntityDef(definition);
      } else {
        // If no matching entity found, clear the definition
        setEntityDef(null);
      }
    }
  }, [items, entityName]);

  // Fetch on mount and when entityName changes
  useEffect(() => {
    fetchEntityDefinition();
  }, [fetchEntityDefinition]);

  // Generate optimized API routes for dynamic entity
  const dynamicApiRoutes = useMemo<DynamicApiRoutes | null>(() => {
    if (!entityName) return null;
    
    const baseEndpoint = `/${entityName}`;
    
    return {
      get: {
        method: 'POST',
        endpoint: baseEndpoint,
        identifier: `GetAll_${entityName}`,
      },
      create: {
        method: 'PUT',
        endpoint: baseEndpoint,
        identifier: `Add_${entityName}`,
      },
      update: {
        method: 'POST',
        endpoint: baseEndpoint,
        identifier: `Update_${entityName}`,
      },
      delete: {
        method: 'DELETE',
        endpoint: baseEndpoint,
        identifier: `Delete_${entityName}`,
      },
    };
  }, [entityName]);


  // Basic columns - dynamic columns will be generated by GenericCrudPage
  const defaultColumns = useMemo(() => [
    {
      title: 'ID',
      dataIndex: '_id',
      key: '_id',
      render: (text: string) => (
        <span style={{ 
          fontFamily: 'monospace', 
          fontSize: '13px',
          fontWeight: 500,
          color: '#1890ff'
        }}>
          {text.substring(0, 8)}...
        </span>
      ),
    },
    {
      title: 'Created',
      dataIndex: 'createdAt',
      key: 'createdAt',
      render: (date: string) => (
        <span style={{ fontSize: '13px', color: '#666' }}>
          {new Date(date).toLocaleDateString()}
        </span>
      ),
    },
    {
      title: 'Updated',
      dataIndex: 'updatedAt',
      key: 'updatedAt',
      render: (date: string) => (
        <span style={{ fontSize: '13px', color: '#666' }}>
          {new Date(date).toLocaleDateString()}
        </span>
      ),
    },
  ], []);

  // Validation helpers
  const isEntityValid = useMemo(() => {
    return Boolean(entityDef && entityDef.is_active);
  }, [entityDef]);

  const hasError = useMemo(() => {
    return error || (!loading && !isEntityValid);
  }, [error, loading, isEntityValid]);

  // Navigation helpers
  const goBack = useCallback(() => {
    navigate('/entities');
  }, [navigate]);

  const goToEntityDefinitions = useCallback(() => {
    navigate('/entity-definitions');
  }, [navigate]);

  return {
    // State
    entityName,
    entityDef,
    loading,
    error,
    hasError,
    isEntityValid,
    
    // Computed
    dynamicApiRoutes,
    defaultColumns,
    
    // Actions
    fetchEntityDefinition,
    goBack,
    goToEntityDefinitions,
    
    // Helpers
    entityDefRoute,
  };
};
